# 列出 Rust 工具链公共入口
[group('meta')]
default:
    @just --list

# 构建指定 Rust 包（默认全部 workspace）
[group('build')]
[no-cd]
build *args="--workspace":
    cargo build {{ args }}

# 运行 Rust 包测试（默认全部 workspace）
[group('test')]
[no-cd]
test *args="--workspace":
    cargo test {{ args }} -- --nocapture

# 检查 Rust 包代码问题（默认全部 workspace）
[group('lint')]
[no-cd]
lint *args="--workspace":
    cargo clippy {{ args }} --fix --allow-dirty --all-targets -- -D warnings

# 格式化 Rust 包（默认全部 workspace）
[group('fmt')]
[no-cd]
fmt *args="--all":
    cargo fmt {{ args }}

# 安装指定 Rust 包
[group('build')]
[no-cd]
install pkg:
    cargo install --path ./rustpkg/{{ pkg }}
